spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/granja
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

server:
  port: 8080

# opcional p/ ver auto-config
# debug: true
